# Generated by Django 4.1.7 on 2023-03-22 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='executors',
            field=models.ManyToManyField(blank=True, null=True, related_name='list_executors', to=settings.AUTH_USER_MODEL),
        ),
    ]
