# Generated by Django 4.1.7 on 2023-04-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_vacancy_executors'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
