# Generated by Django 4.1.7 on 2023-04-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_vacancy_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
