# Generated by Django 4.1.7 on 2023-06-23 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0005_alter_vacancy_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='executor',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='executor',
            field=models.ManyToManyField(blank=True, related_name='final_executor', to=settings.AUTH_USER_MODEL),
        ),
    ]
